**python Numpy Array Concatenation and split**

In [1]:
import numpy as np


In [2]:
arr1=np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
arr2=np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [5]:
np.concatenate((arr1,arr2)) # concatenate function is concatenate two matix by column by

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [6]:
# row by concatenate
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [7]:
# another way to concatenate by vstack by vertical
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [8]:
# horizontal concatenate by hstack 
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

**split function**

In [11]:
list=np.split(arr1,2)
print(list)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [12]:
type(list)
# split function split array and store in list 

list

In [13]:
list[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
type(list[0])

numpy.ndarray

In [16]:
# row by split
np.split(arr1,2,axis=1)
# 2 means same part divide


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [17]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
d1=np.array([1,3,5,6,4])

In [22]:
np.split(d1,[1,3])
# inside the split that is index and 
# give the number of index but if we give 1 then it print before one
# 1 vanda agadiko value then 3 means 3 vanda agadiko value 

[array([1]), array([3, 5]), array([6, 4])]

In [24]:
np.split(d1,[0,2])

[array([], dtype=int32), array([1, 3]), array([5, 6, 4])]