# Numpy Function :


In [2]:
import numpy as np


**arange()**




In [4]:
# particutular value range 
# syntax np.arange(star,End,steps)
ar_1d=np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
type(ar_1d)

numpy.ndarray

even_ar=np.arange(1,13,2)
print(even_ar)

**linspace()**

In [10]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

**reshape()**

In [11]:
ar_1d=np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [12]:
# change to 2d arrage by reshape()
ar_2d=ar_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [14]:
ar_3d=ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [15]:
ar_3d=ar_1d.reshape(3,2,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [16]:
ar_3d=ar_1d.reshape(2,2,3)
print(ar_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
ar=np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


**ravel()**

In [ ]:
##  convert multidimensional array to 1-d array

In [20]:
ar.ravel()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**flatten()**

In [21]:
# convert multidimensional array to 1d
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**transpose()**


In [22]:
#convert row to column

ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])