In [1]:
import numpy as np

In [2]:
arr_1d=np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
arr_1d

array([1, 2, 3, 4])

In [4]:
arr_1d.dtype

dtype('int32')

In [5]:
type(arr_1d)

numpy.ndarray

In [6]:
ad=np.ones((3,4))
ad

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
sa=np.zeros((2,2))
sa

array([[0., 0.],
       [0., 0.]])

In [8]:
ad=np.ones((2,2),dtype=str)
ad

array([['1', '1'],
       ['1', '1']], dtype='<U1')

In [9]:
em=np.empty((2,2))
em

array([[0., 0.],
       [0., 0.]])

In [10]:
e=np.empty((3,3))
e

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 5.99e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [11]:
add=np.empty((2,2))
add

array([[0., 0.],
       [0., 0.]])

In [12]:
add=np.empty((6,6))
add

array([[0.00000000e+000, 0.00000000e+000, 9.96590475e-312,
        3.41628492e-312, 2.61054848e+106, 0.00000000e+000],
       [            nan, 0.00000000e+000, 0.00000000e+000,
        7.41098469e-323, 0.00000000e+000, 2.42092166e-322],
       [0.00000000e+000, 9.96578779e-312, 9.96578779e-312,
        9.96578779e-312, 9.96578779e-312, 9.96578778e-312],
       [8.91238232e-313, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [2.11377150e-314, 6.32404027e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [13]:
ad=np.arange(1,13)
ad

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
ad=np.arange(1,12,2)
ad

array([ 1,  3,  5,  7,  9, 11])

In [15]:
ad=np.linspace(1,5,4)
ad

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [16]:
ad=np.linspace(1,5,7)
ad

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [17]:
ad=np.arange(1,13)
ab=ad.reshape(2,6)
ab

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
ac=ab.reshape(2,3,2)
ac

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [19]:
ac=ab.reshape(3,2,2)
ac

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [20]:
ad=ac.ravel()
ad

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
ab=ac.flatten()
ab

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
ad=np.arange(1,13)
ab=ad.reshape(2,6)
ab


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [23]:
ac=ab.transpose()
ac

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [24]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
b=a.transpose()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(1,10).reshape(3,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [28]:
np.add(a,b)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [29]:
a-b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
np.subtract(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [32]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [33]:
a/b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.divide(a,b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
ab=np.arange(1,5).reshape(2,2)
ab

array([[1, 2],
       [3, 4]])

In [36]:
bc=np.arange(1,5).reshape(2,2)
bc

array([[1, 2],
       [3, 4]])

In [37]:
ab.dot(bc)

array([[ 7, 10],
       [15, 22]])

In [38]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a.max()

9

In [40]:
a.argmax()


8

In [41]:
a.max(axis=0)

array([7, 8, 9])

In [42]:
a.max(axis=1)

array([3, 6, 9])

In [43]:
a.min()

1

In [44]:
a.min(axis=1)

array([1, 4, 7])

In [45]:
a.mean()

5.0

In [46]:
a.mean(axis=1)

array([2., 5., 8.])

In [47]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
a.mean(axis=0)

array([4., 5., 6.])

In [49]:
a.min(axis=0)

array([1, 2, 3])

In [50]:
np.mean(a,axis=0)

array([4., 5., 6.])

In [51]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [52]:
np.std(a)

2.581988897471611

In [53]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [54]:
mx=np.arange(1,26).reshape(5,5)
mx

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
mx[0,0]

1

In [56]:
mx[0]

array([1, 2, 3, 4, 5])

In [57]:
mx[0,0].ndim

0

In [58]:
mx[:,0].ndim

1

In [59]:
mx[:,0]

array([ 1,  6, 11, 16, 21])

In [60]:
mx[0:1]

array([[1, 2, 3, 4, 5]])

In [61]:
mx[:,0:1]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [62]:
mx[0:1,:]

array([[1, 2, 3, 4, 5]])

In [63]:
mx

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
mx[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [65]:
mx[0,1]

2

In [66]:
mx[1,1]

7

In [67]:
mx[1,0]

6

In [68]:
mx

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [69]:
mx[1:3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [72]:
mx[2,1]

12

In [73]:
a=np.arange(1,17).reshape(4,4)
b=np.arange(17,33).reshape(4,4)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [75]:
np.concatenate((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [76]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [77]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [78]:
np.hstack((a,b))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [80]:
np.split(a,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [81]:
np.split(a,4,axis=1)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [84]:
np.split(a,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [85]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [86]:
import random

In [87]:
np.random.random(1)

array([0.7008294])

In [90]:
np.random.random((3,3))

array([[0.89430474, 0.48809377, 0.65506031],
       [0.53856086, 0.60739352, 0.6913755 ],
       [0.50661007, 0.46514337, 0.82390557]])

In [91]:
np.random.randint(1,4)

1

In [92]:
 np.random.randint(1,55,(4,4))

array([[43, 33, 48,  6],
       [46, 48, 50,  2],
       [21, 21, 13, 11],
       [35, 33, 49, 27]])

In [93]:
for i in range(10):

SyntaxError: unexpected EOF while parsing (<ipython-input-93-e61162350cc4>, line 1)

In [94]:
x=[1,2,3,4,5]
for  i in range(10):
    print(np.random.choice(x))

3
1
1
5
1
4
3
3
3
3


In [95]:
 np.random.permutation(x)

array([5, 4, 3, 1, 2])

In [96]:
np.random.randn(3)

array([-0.26286201, -1.17039451,  1.54541874])

In [97]:
np.random.randn(3,3)

array([[-0.37956937,  1.09687122,  0.55044336],
       [-0.7683418 , -0.22376011, -0.08831811],
       [-0.02899636, -0.11159123, -0.14960131]])

In [98]:
a='my name is ajay'
a

'my name is ajay'

In [99]:
b='i read in sscc'
np.char.add(a,b)

array('my name is ajayi read in sscc', dtype='<U29')

In [100]:
np.char.add(a,b).dtype

dtype('<U29')

In [101]:
ab=np.char.add(a,b)
type(ab)

numpy.ndarray

In [103]:
bb=np.array([1,2,3,4])
bb

array([1, 2, 3, 4])

In [104]:
type(bb)

numpy.ndarray

In [105]:
bb.dtype

dtype('int32')

In [106]:
bb.ndim

1

In [107]:
a

'my name is ajay'

In [108]:
np.char.split(a)

array(list(['my', 'name', 'is', 'ajay']), dtype=object)

In [112]:
np.char.center(a,20,fillchar="*")

array('**my name is ajay***', dtype='<U20')

In [113]:
a='dmy'
b='dmy'
np.char.join([':',"/"],[a,b])

array(['d:m:y', 'd/m/y'], dtype='<U5')

In [114]:
a='my name is ajay'
b='my name is sanjay'
np.char.equal(a,b)

array(False)

In [115]:
np.char.count(a,'a')

array(3)

In [116]:
np.char.count(b,'a').dtype

dtype('int32')

In [118]:
np.char.find(a,'name')

array(3)

In [119]:
a=[1,2,3,'data values']
a

[1, 2, 3, 'data values']

In [123]:
import pandas as pd

In [124]:
b=pd.Series(a)
b

0              1
1              2
2              3
3    data values
dtype: object

In [130]:
w=pd.Series([1,2,3],index=['a','b','c'])
w

a    1
b    2
c    3
dtype: int64

In [131]:
h=pd.Series(w,dtype=float)
h

a    1.0
b    2.0
c    3.0
dtype: float64

In [133]:
pd.Series(h,name='data value')

a    1.0
b    2.0
c    3.0
Name: data value, dtype: float64

In [134]:
a=pd.Series(1,index=[1,2,3])
a

1    1
2    1
3    1
dtype: int64

In [135]:
a=pd.Series({'a':1,'b':2})
a


a    1
b    2
dtype: int64

In [136]:
a=pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [137]:
a[3]

4

In [138]:
a[1:4]

1    2
2    3
3    4
dtype: int64

In [139]:
b=pd.Series([1,2,3])
b

0    1
1    2
2    3
dtype: int64

In [140]:
a+b

0    2.0
1    4.0
2    6.0
3    NaN
4    NaN
dtype: float64

In [142]:
a=pd.DataFrame()
print(a)

Empty DataFrame
Columns: []
Index: []


In [143]:
ab=['a','b','c','d']
ab

['a', 'b', 'c', 'd']

In [144]:
type(ab)

list

In [148]:
c=pd.DataFrame(ab)
c

0
0  a
1  b
2  c
3  d

In [149]:
ls=[[1,2,3],[4,5,6],[6,7,8]]
ls

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [150]:
c=pd.DataFrame(ls)
c

0  1  2
0  1  2  3
1  4  5  6
2  6  7  8

In [151]:
c

0  1  2
0  1  2  3
1  4  5  6
2  6  7  8

In [158]:
dict={'id':[1,2,3]}
dict

{'id': [1, 2, 3]}

In [159]:
dict=pd.DataFrame(dict)
dict

id
0   1
1   2
2   3

In [163]:
dict={'id':[1,2,3,4],'sn':['a','b','c','d']}
dict

{'id': [1, 2, 3, 4], 'sn': ['a', 'b', 'c', 'd']}

In [164]:
p=pd.DataFrame(dict)
p

id sn
0   1  a
1   2  b
2   3  c
3   4  d

In [167]:
a={'id': pd.Series([1,2,3,4]),'sn':[11,22,33,44]}
a

{'id': 0    1
 1    2
 2    3
 3    4
 dtype: int64,
 'sn': [11, 22, 33, 44]}

In [168]:
b=pd.DataFrame(a)
b

id  sn
0   1  11
1   2  22
2   3  33
3   4  44

In [173]:
pd.read_csv('E:\\a.csv')

Student ID  Class  Study hrs  Sleeping H  GP  Percentage
0      1001.0      8          2         9.0   5         NaN
1      1002.0      8          6         8.0   0        50.0
2      1003.0      9          3         8.0   2        80.0
3      1004.0     10          0         1.0   0        45.0
4      1005.0     10          4         3.0   3        70.0
5      1006.0     12         10         6.0   5        62.0
6         NaN     13          4         9.0   4        90.0
7      1007.0      9         10         0.0   0        88.0
8      1008.0     10          2         0.0   0        60.0
9      1009.0      7          6         NaN   0        59.0

In [177]:
pd.read_excel('E:\\Book1.xlsx')

Student ID  Class  Study hrs  Sleeping H  GP  Percentage
0      1001.0      8          2         9.0   5         NaN
1      1002.0      8          6         8.0   0        50.0
2      1003.0      9          3         8.0   2        80.0
3      1004.0     10          0         1.0   0        45.0
4      1005.0     10          4         3.0   3        70.0
5      1006.0     12         10         6.0   5        62.0
6         NaN     13          4         9.0   4        90.0
7      1007.0      9         10         0.0   0        88.0
8      1008.0     10          2         0.0   0        60.0
9      1009.0      7          6         NaN   0        59.0