**Random sampling with numpy**

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.44335105])

In [4]:
np.random.random((3,3))

array([[0.62875693, 0.74853193, 0.49376645],
       [0.41493362, 0.68964727, 0.03865651],
       [0.36796883, 0.55292084, 0.22212412]])

In [5]:
# value for integer randint
np.random.randint(1,4)

2

In [6]:
np.random.randint(1)

0

In [7]:
np.random.randint(1,4,(4,4))
# randint 1,4 is range of 4 by 4 matix

array([[1, 2, 3, 1],
       [1, 2, 2, 3],
       [1, 3, 2, 3],
       [2, 2, 2, 1]])

In [8]:
np.random.randint(1,5,(2,4,4))

array([[[1, 1, 4, 3],
        [2, 4, 1, 2],
        [3, 2, 3, 2],
        [4, 4, 1, 1]],

       [[4, 4, 4, 4],
        [1, 1, 2, 3],
        [1, 4, 4, 3],
        [3, 1, 1, 1]]])

In [9]:
# same value which is generate above
np.random.seed(10)
np.random.randint(1,5,(2,4,4))

array([[[2, 2, 1, 4],
        [1, 2, 4, 1],
        [2, 2, 1, 2],
        [2, 3, 1, 2]],

       [[1, 3, 1, 3],
        [1, 4, 1, 1],
        [4, 4, 3, 1],
        [4, 3, 3, 2]]])

In [10]:
# for same value in above
np.random.seed(10)
np.random.randint(1,5,(2,4,4))

array([[[2, 2, 1, 4],
        [1, 2, 4, 1],
        [2, 2, 1, 2],
        [2, 3, 1, 2]],

       [[1, 3, 1, 3],
        [1, 4, 1, 1],
        [4, 4, 3, 1],
        [4, 3, 3, 2]]])

In [11]:
np.random.rand(3)

array([0.72175532, 0.29187607, 0.91777412])

In [12]:
np.random.rand(3,3)
# only show o to 1 value in random

array([[0.71457578, 0.54254437, 0.14217005],
       [0.37334076, 0.67413362, 0.44183317],
       [0.43401399, 0.61776698, 0.51313824]])

In [13]:
np.random.randn(3)

array([1.12369125, 1.67262221, 0.09914922])

In [14]:
np.random.randn(3,3)
# give negative and positive value

array([[ 1.39799638, -0.27124799,  0.61320418],
       [-0.26731719, -0.54930901,  0.1327083 ],
       [-0.47614201,  1.30847308,  0.19501328]])

In [15]:
# permutation for shuffle
x=[1,2,3,4]
np.random.permutation(x)

array([3, 2, 4, 1])

In [16]:
np.random.permutation(x)

array([2, 3, 4, 1])